In [1]:
import numpy as np

a = np.array([[1,2,3,4],[1,3,4,5],[9,8,7,6]])
print(a)

[[1 2 3 4]
 [1 3 4 5]
 [9 8 7 6]]


In [2]:
# number of Dimentions
a.ndim

2

In [3]:
# Data type
a.dtype

dtype('int32')

In [4]:
# Total number of elements
a.size

12

In [5]:
# size of each element
a.itemsize

4

In [6]:
# size(bytes) of matrix
a.size * a.itemsize

48

In [7]:
# size in bytes
a.nbytes

48

In [8]:
print(a)

[[1 2 3 4]
 [1 3 4 5]
 [9 8 7 6]]


In [9]:
a[0,3]

4

In [10]:
a[0,:]

array([1, 2, 3, 4])

In [11]:
a[1,:]

array([1, 3, 4, 5])

In [12]:
a[:,0]

array([1, 1, 9])

In [13]:
print(a)

[[1 2 3 4]
 [1 3 4 5]
 [9 8 7 6]]


In [14]:
a[1, 0:3:2]

array([1, 4])

In [15]:
# changing specific element
a[1,1] = 99
a

array([[ 1,  2,  3,  4],
       [ 1, 99,  4,  5],
       [ 9,  8,  7,  6]])

In [16]:
a[:, 1] = 0
a

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6]])

# 3D Matrix

In [17]:
b = np.array([[[1,2,3,4],[6,7,8,9]]])
b

array([[[1, 2, 3, 4],
        [6, 7, 8, 9]]])

In [18]:
print(b)

[[[1 2 3 4]
  [6 7 8 9]]]


In [19]:
b[0,1,1]

7

# Types of Arrays

In [20]:
# Zero Matrix takes 'Tuple'
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# Full matrix creates nxm matrinx with Given element>>>>> ((typle), element)
np.full((2,3), 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [22]:
# creates an matrix just like Matrix 'a' with 99
np.full_like(a, 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [23]:
# creates 3x2 matrix with random numbers
np.random.rand(3,2)

array([[0.49862169, 0.99996411],
       [0.59231819, 0.54763553],
       [0.80705231, 0.59428471]])

In [24]:
# 4x3 matrix with random values less than 5
np.random.randint(5, size=(4,3))

array([[3, 1, 4],
       [3, 2, 3],
       [1, 2, 4],
       [3, 0, 0]])

In [25]:
# identity matrix 3x3
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
a

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6]])

In [27]:
# repeating an array "Repeats each column"
b = np.repeat(a, 2, axis=0)
b

array([[1, 0, 3, 4],
       [1, 0, 3, 4],
       [1, 0, 4, 5],
       [1, 0, 4, 5],
       [9, 0, 7, 6],
       [9, 0, 7, 6]])

# Copying an array

In [28]:
# c=a will give error
c = a.copy()
c

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6]])

# Mathematics

In [29]:
a

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6]])

In [30]:
b

array([[1, 0, 3, 4],
       [1, 0, 3, 4],
       [1, 0, 4, 5],
       [1, 0, 4, 5],
       [9, 0, 7, 6],
       [9, 0, 7, 6]])

In [31]:
c[:,1]=6
c[2,:]=3
c

array([[1, 6, 3, 4],
       [1, 6, 4, 5],
       [3, 3, 3, 3]])

In [32]:
# Not a Matrix Multiplication
a*c

array([[ 1,  0,  9, 16],
       [ 1,  0, 16, 25],
       [27,  0, 21, 18]])

In [33]:
a+c

array([[ 2,  6,  6,  8],
       [ 2,  6,  8, 10],
       [12,  3, 10,  9]])

In [34]:
a-c

array([[ 0, -6,  0,  0],
       [ 0, -6,  0,  0],
       [ 6, -3,  4,  3]])

# Task-1

In [35]:
# print the following Array
#    1 1 1 1 1
#    1 0 0 0 1
#    1 0 9 0 1
#    1 0 0 0 1
#    1 1 1 1 1

In [36]:
arr1 = np.ones((5,5), dtype='int32')
arr1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
arr2 = np.zeros((3,3),dtype='int32')
arr2[1,1]=9
arr2

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [38]:
arr1[1:4,1:4] = arr2

In [39]:
print(arr1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Linear Algebra


In [40]:
x=np.ones((3,4), dtype='int32')
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
y=np.full((4,3), 2)
y

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
# Matrix Multiplication
np.matmul(x,y)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [43]:
# similarly we can find
# 1-inverse
# 2-Trace
# 3-Matrix norm
# etc

# Statistics

In [44]:
a

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6]])

In [45]:
np.min(a)

0

In [46]:
np.max(a)

9

In [47]:
np.sum(a)

40

# Reorganizing an Array

In [48]:
a.shape

(3, 4)

In [49]:
a

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6]])

In [50]:
l=a.reshape((4,3))
l

array([[1, 0, 3],
       [4, 1, 0],
       [4, 5, 9],
       [0, 7, 6]])

In [51]:
# Vertical Stacking
np.vstack([a,x])

array([[1, 0, 3, 4],
       [1, 0, 4, 5],
       [9, 0, 7, 6],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
# Horizantol Stacking
np.hstack([a,x])

array([[1, 0, 3, 4, 1, 1, 1, 1],
       [1, 0, 4, 5, 1, 1, 1, 1],
       [9, 0, 7, 6, 1, 1, 1, 1]])

# Loading Data from File

In [53]:
# file = np.genfromtxt('data.txt', delimiter=',')
# file.dtype('int32')

# Boolean Masking

In [54]:
a > 5

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False,  True,  True]])

In [55]:
a[a>5]

array([9, 7, 6])

In [56]:
# is any element in Matrix 'a' Greater than >5
np.any(a>5)

True

In [57]:
# Are all Elements in Matrix 'a' Greater than >5
np.all(a>5)

False

# Task-2

In [58]:
# select 1 2 from the following Matrix
#        1 2

#    1 2 3 4 5 6
#    2 1 3 4 5 6 
#    9 8 7 6 5 4

In [59]:
arr3 = np.array([[1,2,3,4,5,6],[2,1,3,4,5,6],[9,8,7,6,5,4],[1, 1, 1, 1, 1, 2]])
arr3

array([[1, 2, 3, 4, 5, 6],
       [2, 1, 3, 4, 5, 6],
       [9, 8, 7, 6, 5, 4],
       [1, 1, 1, 1, 1, 2]])

In [60]:
arr3[0:2,0:2]

array([[1, 2],
       [2, 1]])

In [61]:
#  select 3  from the following Matrix
#          4
#           5
#            2
    

#      1 2 3 4 5 6
#      2 1 3 4 5 6 
#      9 8 7 6 5 4
#      1 1 1 1 1 2

In [62]:
arr3

array([[1, 2, 3, 4, 5, 6],
       [2, 1, 3, 4, 5, 6],
       [9, 8, 7, 6, 5, 4],
       [1, 1, 1, 1, 1, 2]])

In [63]:
arr3[[0,1,2,3],[2,3,4,5]]

array([3, 4, 5, 2])